Restaurant.create(name: "dolores",address: "mitte",category: "italian")
Restaurant.create(name: "Mcd",address: "pberg",category: "chinese")
Restaurant.create(name: "kebabshop",address: "wedding",category: "japanese")
Restaurant.create(name: "santa maria",address: "kreuzberg",category: "french")
Restaurant.create(name: "stranero",address: "berlin",category: "belgian")
